# Generated by Django 4.1.5 on 2023-02-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Categoria',
        ),
    ]
