# Generated by Django 4.1.5 on 2023-02-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_producto_categoria'),
        ('productos', '0002_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
